RPGManager/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from rpg_apps.functs.main import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('rpg_apps.functs.main.urls', namespace='main')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rpg_apps/functs/main/urls.py
from django.conf.urls import url
from rpg_apps.functs.main import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^index$', views.index, name='index'),
    url(r'^login$', auth_views.LoginView.as_view(template_name='functs/main/login.html',
                                                redirect_field_name='/main/games'),
        name='login'),
    url(r'logout', auth_views.LogoutView.as_view(next_page='/main/index'),
        name='logout'),
    url(r'^register$', views.register, name='register'),
    url(r'^games$', views.games, name='games'),
    url(r'^games/([0-9]+)$', views.game_properties, name='games'),
    url(r'^new_game$', views.new_game, name='new_game'),
    url(r'^send$', views.send, name='send'),
    url(r'^invite$', views.invites, name='invite'),
    url(r'^invite_game$', views.invite_game, name='invite_game'),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rpg_apps/functs/charsheet/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

rpg_apps/functs/gmscreen/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

rpg_apps/functs/main/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    """This model is an extension of the default User model,
        its purpose is to hide the username of the user in order
        to improve security a little."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=51, primary_key=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)


class RPG(models.Model):
    """This models contains all the games that are usable in the app."""
    slug = models.SlugField(max_length=10, blank=False, unique=True)
    name = models.CharField(max_length=100, blank=False)
    img = models.ImageField(upload_to='main', blank=False)
    simg = models.ImageField(upload_to='main', blank=False)
    desc = models.TextField(max_length=255)

    def __str__(self):
        return self.name

class UserGame(models.Model):
    OBSERVER = 0
    PLAYER = 1
    CONTRIB = 2
    OWNER = 3
    game = models.ForeignKey("Game", blank=False)
    user = models.ForeignKey(User, blank=False, on_delete=models.CASCADE)
    permissions = models.IntegerField(default=0, blank=False, choices=(
                        (OBSERVER, 'Observer'), (PLAYER, 'Player'), (CONTRIB, 'Contrib'), (OWNER, 'Owner')))
    accepted = models.BooleanField(default=False)

    class Meta:
        unique_together = ('game', 'user')


class Game(models.Model):
    owner = models.ForeignKey(UserGame, blank=False, on_delete=models.CASCADE, related_name="game_owner")
    name = models.CharField(max_length=100, blank=False)
    rpg = models.ForeignKey(RPG, blank=False)
    desc = models.TextField(max_length=255, default=None)
    next_date = models.DateTimeField(blank=True, null=True, default=None)

    def __str__(self):
        return self.name + " --- " + self.rpg.__str__()

    class Meta:
        unique_together = ('owner', 'name', 'rpg')


class Message(models.Model):
    user_from = models.ForeignKey(User, blank=False, related_name="msg_orig")
    user_to = models.ForeignKey(User, blank=False, related_name="msg_dest")
    date = models.DateTimeField(auto_now_add=True, blank=False)
    text = models.CharField(max_length=255, blank=False)
    seen = models.BooleanField(default=False)


class Invite(models.Model):
    user_from = models.ForeignKey(User, blank=False, related_name="inv_orig")
    user_to = models.ForeignKey(User, blank=False, related_name="inv_dest")
    game = models.ForeignKey(UserGame, blank=False)
    date = models.DateTimeField(auto_now_add=True, blank=False)

rpg_apps/games/dl/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

rpg_apps/games/sr/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

rpg_apps/games/vtm/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

rpg_apps/functs/main/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth.models import User
from rpg_apps.functs.main.models import UserProfile, Game, Message, UserGame


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'password', 'email')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)


class NewGameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ('name', 'rpg', 'desc')
    date = forms.DateField(
        widget=widgets.SelectDateWidget(empty_label=('Year', 'Month', 'Day'))
    )
    time = forms.TimeField(widget=widgets.TimeInput())

    def save(self, commit=True):
        self.cleaned_data['next_data'] = self.cleaned_data['date'] + ' ' + self.cleaned_data['time']
        super(NewGameForm, self).save(commit=commit)


class SendMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('user_to', 'text')


class InviteGameForm(forms.ModelForm):

    def __init__(self, current_user, *args, **kwargs):
        super(InviteGameForm, self).__init__(*args, **kwargs)
        self.fields['user'].queryset = self.fields['user'].queryset.exclude(id=current_user.id)
        self.fields['game'].queryset = self.fields['game'].queryset.filter(user=current_user.id)

    class Meta:
        model = UserGame
        fields = ('game', 'user')
    permissions = forms.ChoiceField(choices=((UserGame.OBSERVER, 'Observer'),
                    (UserGame.PLAYER, 'Player'),(UserGame.CONTRIB, 'Contrib')))

rpg_apps/functs/charsheet/views.py
from django.shortcuts import render

# Create your views here.

rpg_apps/functs/gmscreen/views.py
from django.shortcuts import render

# Create your views here.

rpg_apps/functs/main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from rpg_apps.functs.main.models import RPG, Game, UserGame
from rpg_apps.functs.main.forms import UserForm, UserProfileForm, NewGameForm


def index(request):
    rpgs = RPG.objects.all()
    return render(request, 'functs/main/index.html', {'rpgs': rpgs})


def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            user_profile = user_profile_form.save(commit=False)
            user_profile.user = user
            user_profile.save()
            return HttpResponseRedirect('/main/login')
        else:
            if not user_form.is_valid():
                print user_form.errors
            if not user_profile_form.is_valid():
                print user_profile_form.errors
    else:
        user_form = UserForm()
        user_profile_form = UserProfileForm()
    context_dict = {'user_form': user_form,
                    'user_profile_form': user_profile_form}
    return render(request, 'functs/main/register.html', context_dict)


def games(request):
    user = request.user
    context_dict = {}
    games_all = Game.objects.all().values(
        'rpg__name', 'rpg__simg', 'rpg__name', 'user__username',
        'name', 'desc', 'next_date', 'pk')
    context_dict['games'] = games_all
    if user.is_authenticated():
        pass
    else:
        pass
    return render (request, 'functs/main/games.html', context_dict)


def game_properties(request, id):
    try:
        game = Game.objects.get(pk=id)
        usergame = UserGame.objects.get(game=game, user=request.user).values()
        rpg = game.select_related('rpg')
        owner = game.select_related('user')
        if request.POST:
            pass
        else:
            pass
        players = UserGame.objects.filter(game=game)
        context_dict = {'game' : game, 'players' : players,
                        'usergame' : usergame, 'rpg' : rpg, 'owner': owner}
        return render(request, 'functs/main/games_properties.html', context_dict)
    except Exception as e:
        print e
        return HttpResponseRedirect('/main/games')


@login_required
def new_game(request):
    context_dict = {}
    if request.method == 'POST':
        newgame_form = NewGameForm(data=request.POST)
        if newgame_form.is_valid():
            try:
                newg = newgame_form.save(commit=False)
                newg.user = request.user
                newg.save()
                user_game = UserGame()
                user_game.game = newg
                user_game.user = request.user
                user_game.permissions = UserGame.CREATOR
                user_game.save()
            except IntegrityError:
                context_dict['integrity_error'] = 'That game name already exists.'
            else:
                HttpResponseRedirect('/games/')
        else:
            print newgame_form.errors
    else:
        newgame_form = NewGameForm()
    context_dict['newgame_form'] = newgame_form
    return render(request, 'functs/main/newgame.html', context_dict)


@login_required
def send(request):
    if request.method == 'POST':
        send_form = SendMessageForm(data=request.POST)
        if send_form.is_valid():
            send_form.save()
            send_form = SendMessageForm()
        else:
            print send_form.errors
    else:
        send_form = SendMessageForm()
    context_dict = {'send_form': send_form }
    return render(request, 'functs/mail/send.html', context_dict)


@login_required
def invites(request):
    if request.method == 'POST':
        inv_pk = request.POST['game']
        try:
            invite = Invite.objects.get(game=int(inv_pk), user_to=request.user)
            game = UserGame.objects.get(pk=invite.game)
            if 'invite_accept' in request.POST:
                text = "The user " + request.user + " has accepted" + \
                       " your invitation for the game " + inv_pk
                game.accepted = True
                game.save()
            else:
                text = "The user " + request.user + " has declined" + \
                        " your invitation for the game " + inv_pk
                game.delete()
            invite.delete()
        except Invite.DoesNotExist:
            pass
    invites = Invite.objects.filter(user_to=request.user)\
        .values('pk','user_from__username','game__game__name', 'date')
    context_dict = {'invites': invites}
    return render(request, 'functs/mail/invites.html', context_dict)


@login_required
def invite_game(request):
    context_dict = {}
    if request.method == 'POST':
        print request.POST
        invite_form = InviteGameForm(current_user=request.user, data=request.POST)
        if invite_form.is_valid():
            user_game = invite_form.save()
            message = Invite(user_from=request.user,
                        user_to=user_game.user, game=user_game)
            message.save()
            context_dict['msg_success'] = "User invite sent."
            invite_form = InviteGameForm(current_user=request.user)
        else:
            print invite_form.errors
    else:
        invite_form = InviteGameForm(current_user=request.user)
    context_dict['invite_form'] = invite_form
    return render(request, 'functs/mail/invitegame.html', context_dict)

rpg_apps/games/dl/views.py
from django.shortcuts import render

# Create your views here.

rpg_apps/games/sr/views.py
from django.shortcuts import render

# Create your views here.

rpg_apps/games/vtm/views.py
from django.shortcuts import render

# Create your views here.

templates/functs/main/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
        {% block extra_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
        {% endblock extra_css %}
        {% block extra_js %}
        {% endblock extra_js %}
        {% block extra_head %}
        {% endblock extra_head %}
        <title>{% block title %}Just the base{% endblock title %}</title>
    </head>
    <body>
        <header>
            {% block header %}
                <h1>[Insert header here]</h1>
            {% endblock header %}
        </header>
        <nav>
            {% block nav %}
            <ul>
                <li class="left"><a href="{% url 'main:index' %}">Home</a></li>
                <li class="left"><a href="{% url 'main:games' %}">Games</a></li>
                {% if user.is_authenticated %}
                    <li class="left"><a href="{% url 'mail:invite_game' %}">Invite Game</a></li>
                    <li class="left"><a href="{% url 'main:new_game' %}">New Game</a></li>
                    <li class="right"><a href="{% url 'main:logout' %}">Logout</a></li>
                    <li class="right"><p>Logged in as {{ user.username }}</p></li>
                    <li class="right"><a href="{% url 'mail:send' %}">Send Message</a></li>
                    <li class="right"><a href="{% url 'mail:invite' %}">Game Invites</a></li>
                {% else %}
                    <li class="right"><a href="{% url 'main:login' %}">Login</a></li>
                    <li class="right"><a href="{% url 'main:register' %}">Register</a></li>
                {% endif %}
            </ul>
            {% endblock nav %}
        </nav>
        <section>
            {% block section %}
                [Insert section content here]
            {% endblock section %}
        </section>
        <footer>
            {% block footer %}
            <p>
                RPG Manager by Jesualdo Garc&iacute;a L&oacute;pez.
            </p>
            {% endblock footer %}
        </footer>
    </body>
</html>

templates/functs/main/games.html
{% extends 'functs/main/base.html' %}
{% load staticfiles %}

{% block title %}Games{% endblock title %}

{% block header %}
    <h1>Games</h1>
{% endblock header %}

{% block section %}
    <h2>Games</h2>
    <table id="game_table">
        <tr>
            <th>Image</th>
            <th>RPG Name</th>
            <th>Game Name</th>
            <th>Owner</th>
            <th>Next Date</th>
            <th>Description</th>
        </tr>
        {% for game in games %}
            <tr>
                <td class="center">
                    <img src="{{ MEDIA_URL }}main/{{ game.rpg__simg }}"
                         alt="{{ game.rpg__simg }}"
                         class="logo">
                </td>
                <td class="center">{{ game.rpg__name }}</td>
                <td><a href="{% url 'main:games' game.pk %}">{{ game.name }}</a></td>
                <td>{{ game.user__username }}</td>
                <td>{{ game.next_date }}</td>
                <td>{{ game.desc }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock section %}

templates/functs/main/games_properties.html
{% extends 'functs/main/base.html' %}
{% load staticfiles %}

{% block title %}{{ game.name }{% endblock title %}

{% block header %}
    <h1>Game Properties</h1>
{% endblock header %}

{% block section %}
    <h2>{{ game.name }}</h2>
    <div>
        <div class="left">
            <div id="game_properties">
                <h3>Properties</h3>
                <img src="{{ MEDIA_URL }}main/{{ rpg.img }}" alt="{{ rpg.img }}">
                <tr>
                    <td><bold>Name</bold></td>
                    <td>{{ game.name }}</td>
                </tr>
                <tr>
                    <td><bold>RPG</bold></td>
                    <td>{{ rpg.name }}</td>
                </tr>
                <tr>
                    <td><bold>Owner</bold></td>
                    <td>{{ owner.name }}</td>
                </tr>
                <p>
                   {{ game.desc }}
                </p>
            </div>
            <div id="game_management">

            </div>
        </div>
        <div id="game_players">

        </div>
    </div>
{% endblock section %}

templates/functs/main/index.html
{% extends 'functs/main/base.html' %}
{% load staticfiles %}

{% block title %}Home{% endblock title %}

{% block header %}<h1>Home</h1>{% endblock header %}

{% block section %}
    <div id="rpgs">
        <h2>RPGs</h2>
        <table>
            {% for rpg in rpgs %}
            <tr>
                <td>
                    <figure>
                        <img src="{{ MEDIA_URL }}main/{{ rpg.img }}"
                                 alt="{{ rpg.img }}">
                       <figcaption class="center">{{ rpg.name }}</figcaption>
                    </figure>
                </td>
                <td>
                    <p>{{ rpg.desc|linebreaks }}</p>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock section %}

templates/functs/main/invitegame.html
{% extends 'functs/main/base.html' %}
{% load staticfiles %}

{% block title %}Invite Game{% endblock title %}

{% block header %}
    <h1>Invite Game</h1>
{% endblock header %}

{% block section %}
    <div id="content">
        <form id="invite_form" method="post" action="{% url 'mail:invite_game' %}">
            {% csrf_token %}

            {% if form.non_field_errors %}
            <div class="error">
                {{ form.non_field_errors }}
            </div>
            {% endif %}
            {% for field in form %}
            <div class="error">
                {{ field.errors }}
            </div>
            {% endfor %}

            {{ invite_form.as_p }}

            {% if msg_success %}
            <div class="success">
                <ul><li>{{ msg_success }}</li></ul>
            </div>
            {% endif %}
            <input type="submit" value="Invite" />
        </form>
    </div>
{% endblock section %}

templates/functs/main/invites.html
{% extends 'functs/main/base.html' %}
{% load staticfiles %}

{% block title %}Game Invites{% endblock title %}

{% block header %}<h1>Game Invites</h1>{% endblock header %}

{% block section %}
    <div id="content">
        <ul>
            {% for invite in invites%}
            <li>
                <form id="send_form" method="post" action="{% url 'mail:invite' %}">
                    {% csrf_token %}
                    <p>
                        The user {{ invite.user_from__username }} has invited you to play
                        {{ invite.game__game__name }} on {{ invite.date }}
                    </p>
                    <input type="hidden" name="game" value="{{ invite.pk }}" />
                    <input type="submit" name="invite_accept" value="Accept" />
                    <input type="submit" name="invite_refuse" value="Refuse" />
                </form>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock section %}

templates/functs/main/login.html
{% extends 'functs/main/base.html' %}
{% load staticfiles %}

{% block title %}Login{% endblock title %}

{% block header %}
    <h1>User Login</h1>
{% endblock header %}

{% block section %}
    <div id="content">
        <form id="login_form" method="post" action="login">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Login" />
        </form>
    </div>
{% endblock section %}

templates/functs/main/newgame.html
{% extends 'functs/main/base.html' %}
{% load staticfiles %}

{% block title %}New Game{% endblock title %}

{% block header %}<h1>New Game</h1>{% endblock header %}

{% block section %}
    <div id="content">
        <form id="newgame_form" method="post" action="{% url 'main:new_game' %}">
            {% csrf_token %}
            {% if integrity_error %}
            <div class="error">
                <ul><li>{{ integrity_error }}</li></ul>
            </div>
            {% endif %}
            {{ newgame_form.as_p }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock section %}

templates/functs/main/register.html
{% extends 'functs/main/base.html' %}
{% load staticfiles %}

{% block title %}Register{% endblock title %}

{% block header %}
    <h1>User Registration</h1>
{% endblock header %}

{% block section %}
    <div id="content">
        <form id="register_forms" method="post" action="register">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ user_profile_form.as_p }}
            <input type="submit" value="Register" />
        </form>
    </div>
{% endblock section %}

templates/functs/main/send.html
{% extends 'functs/main/base.html' %}
{% load staticfiles %}

{% block title %}Send Message{% endblock title %}

{% block header %}<h1>Send Message</h1>{% endblock header %}

{% block section %}
    <div id="content">
        <form id="send_form" method="post" action="{% url 'mail:send' %}">
            {% csrf_token %}
            {{ send_form.as_p }}
            <input type="submit" value="Send" />
            <input type="reset" value="Clear" />
        </form>
    </div>
{% endblock section %}